name: Get lastest release from template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/
          load_mode: skip
      
      - name: Get release from template
        uses: robinraju/release-downloader@main
        with:
          latest: true
          fileName: "release.zip"
          repository: "ObsidianPublisher/follow_template"
      - name: Unzip changed files
        run: |
          unzip -o release.zip
          rm release.zip
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Update from template
          title: "[BUMP] Update from template"
          body: |
            files changed:
            ```
            $(git diff --name-only HEAD^ HEAD)
            ```
          labels: |
            update
          branch: update_repo
          delete-branch: true
      - name: AutoMerging 
        if: ${{ steps.cpr.outputs.pull-request-operation == 'created' && env.AUTO_MERGE == 'true' }}
        uses: peter-evans/enable-pull-request-automerge@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
          
