name: mkdocs_build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - '.github/workflow/**'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[PUBLISHER]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.2
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with: 
          path: requirements.txt
      - run: mkdocs gh-deploy --force --clean
